' ******************************************************************************
' swxJRNL.swj - journal recorded on 11/13/12 by JIPE
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long
Dim Annotation As Object
Dim Gtol As Object
Dim DatumTag As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc4 ("G:\Dropbox\PartageXavier\PTSI\CI_06_PPM\01_Materiaux\png\SW\CC_eclate\CC.SLDASM", 2, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("CC.SLDASM")
Part.WindowRedraw
swApp.ActiveDoc.ActiveView.FrameWidth = 1827
swApp.ActiveDoc.ActiveView.FrameHeight = 892
Part.ActiveView().RotateAboutCenter 0, 0.00787273
Part.ActiveView().RotateAboutCenter 0.08257, 1.01558
Part.ActiveView().RotateAboutCenter 0.008257, 0.212564
Part.ActiveView().RotateAboutCenter -0.008257, 0.118091
Part.ActiveView().RotateAboutCenter -0.0041285, 0.00787273
Part.ActiveView().RotateAboutCenter -0.0041285, 0.251927
Part.ActiveView().RotateAboutCenter 0, 0.551091
Part.ActiveView().RotateAboutCenter 0.0041285, 0.251927
Part.ActiveView().RotateAboutCenter 0, 0.543218
Part.ActiveView().RotateAboutCenter 0, 0.543218
Part.ActiveView().RotateAboutCenter -0.0123855, 0.133836
Part.ActiveView().RotateAboutCenter 0.033028, 0.0393636
Part.ActiveView().RotateAboutCenter 0.057799, 0.0629818
Part.ActiveView().RotateAboutCenter 0.0701845, 0.0236182
Part.ActiveView().RotateAboutCenter 0.0206425, 0
Part.ActiveView().RotateAboutCenter 0.008257, 0
Part.ActiveView().RotateAboutCenter 0.0619275, -0.133836
Part.ActiveView().RotateAboutCenter 0.0206425, -0.1732
Part.ActiveView().RotateAboutCenter 0, -0.118091
Part.ActiveView().RotateAboutCenter 0, -0.0866
Part.ActiveView().RotateAboutCenter 0.0041285, -0.0787273
Part.ActiveView().RotateAboutCenter -0.016514, -0.110218
Part.ActiveView().RotateAboutCenter -0.136241, -0.637691
Part.ActiveView().RotateAboutCenter -0.033028, -0.0393636
Part.ActiveView().RotateAboutCenter -0.074313, -0.102345
Part.ActiveView().RotateAboutCenter -0.0784415, -0.118091
Part.ActiveView().RotateAboutCenter -0.074313, -0.0551091
Part.ActiveView().RotateAboutCenter -0.0206425, -0.0236182
Part.ActiveView().RotateAboutCenter 0, 0.00787273
Part.ActiveView().RotateAboutCenter 0, 0.125964
Part.ActiveView().RotateAboutCenter 0, 0.0551091
Part.ActiveView().RotateAboutCenter 0.0041285, 0.110218
Part.ActiveView().RotateAboutCenter 0.0041285, 0.110218
Part.ActiveView().RotateAboutCenter 0.057799, -0.0944727
Part.ActiveView().RotateAboutCenter 0.0536705, -0.0866
Part.ActiveView().RotateAboutCenter 0.0041285, -0.00787273
Part.ActiveView().RotateAboutCenter 0, -0.00787273
Part.ActiveView().RotateAboutCenter 0.0041285, 0.00787273
Part.ActiveView().RotateAboutCenter 0.049542, 0.0787273
Part.ActiveView().RotateAboutCenter 0.0041285, 0
Part.ActiveView().RotateAboutCenter 0.0206425, 0
Part.ActiveView().RotateAboutCenter 0.0454135, 0
Part.ActiveView().RotateAboutCenter 0.008257, 0.0157455
Part.ActiveView().RotateAboutCenter 0.008257, 0.0787273
Part.ActiveView().RotateAboutCenter 0.0123855, 0.0866
Part.ActiveView().RotateAboutCenter 0.0123855, 0.0787273
Part.ActiveView().RotateAboutCenter 0, 0.0551091
swApp.ExitApp
End Sub
